name: Generate documentation
on: 
  pull_request:
    branches:
      - develop
      - master
      - releasecandidate/*
  workflow_dispatch:

jobs:
  buildDocsGenerator:
    name: Build docs generator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      
      - name: Build docs generator
        run: cd docs_generator && dotnet build Scanner.csproj

      - name: Current state of docs
        run: ls docs && find docs/ -type f -exec md5sum {} \; | md5sum
       
      - name: Clear /docs folder
        run: rm -rf docs/* 
       
      - name: Execute docs runner 
        run: cd unity && ../docs_generator/bin/Debug/net6.0/Scanner

      - name: New state of docs
        run: ls docs && find docs/ -type f -exec md5sum {} \; | md5sum

      - name: Upload '/dodcs' artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs-v${{ github.run_number }}
          path: docs

      - name: Commit report
        run: |
          git config --global user.name 'Vincent Mahnke'
          git config --global user.email 'vimaster@users.noreply.github.com'
          git commit -am "Update /docs"
          git push